### ISSUE TITLE
Worst I-ready Cheat Out ATM

### ISSUE THREAD

**Issue by FlipMods** [Sapphire-Inc/Sapphire#1]
# This is the worst _i-ready_ cheat around

## Let me explain
 
After Saying my Account Got Banned I Got banned from their server which wouldn't be interesting until I noticed that this is a hack that sucks so bad the anticheat picks it up

**Comment by FlipMods** [comment]
Yw @SapphirePlaceholder

**Comment by FlipMods** [comment]
![image](https://github.com/Sapphire-Inc/Sapphire/assets/109514575/5d3c90fe-a4cb-4dc4-9a43-d3742014c117)

**Comment by uhidontkno** [comment]
> # This is the worst _i-ready_ cheat around
> ## Let me explain
> 
> After Saying my Account Got Banned I Got banned from their server which wouldn't be interesting until I noticed that this is a hack that sucks so bad the anticheat picks it up

Motherfucker cannot read the README to realize if you're actually fucking smart it wont ban you. You got banned from the discord for complaining like a dumbass.

**Comment by galaxqy** [comment]
> # This is the worst _i-ready_ cheat around
> ## Let me explain
> After Saying my Account Got Banned I Got banned from their server which wouldn't be interesting until I noticed that this is a hack that sucks so bad the anticheat picks it up

1. i banned you from the discord server because you started complaining nonstop about how the hack sucks ass and how it got your account banned, we stated in the rules that we will ban because it's annoying and nobody cares
2. if you could read any other previous announcements/notices you could read that the hack obviously has a chance of banning.
3. iready has changed their anticheat making the hack more detectable then ever, it is not inherently an issue with sapphire because every other hack/skipper is just as detectable as sapphire.
4. you make your own hack then if your so good at "web development" 💀

**Comment by uhidontkno** [comment]
> 1. i banned you from the discord server because you started complaining nonstop about how the hack sucks ass and how it got your account banned, we stated in the rules that we will ban because it's annoying and nobody cares
> 2. if you could read any other previous announcements/notices you could read that the hack obviously has a chance of banning.
> 3. iready has changed their anticheat making the hack more detectable then ever, it is not inherently an issue with sapphire because every other hack/skipper is just as detectable as sapphire.
> 4. you make your own hack then if your so good at "web development" 💀

His brain is incoherent garbage so therefore he doesn't know how to read.
